// @generated by scripts/sync-playground-component.sh — do not edit.
// Edit registry/data_grid/component.rs instead.
//! A styled data grid, composed from the unstyled primitives in
//! `dioxus-datagrid`.
//!
//! This file is yours once `dx components add` copies it in — change the markup
//! and the classes freely. Sorting, filtering, paging, selection and keyboard
//! navigation live in the `dioxus-datagrid` crate, so they keep improving
//! without you having to re-copy this file.

use dioxus::prelude::*;
use dioxus_datagrid::primitives::{
    GridBody, GridColumnFilter, GridHeader, GridPagination, GridRoot, GridSearch, VirtualGridBody,
};
use dioxus_datagrid::{
    Column, ColumnWidth, GridLocale, GridOptions, GridRow, GridState, SelectionMode, use_grid,
};

const THEME: Asset = asset!("/assets/dx-components-theme.css");
const STYLE: Asset = asset!("/src/components/data_grid/style.css");

/// Props for [`DataGrid`].
#[derive(Props, Clone, PartialEq)]
pub struct DataGridProps<T: GridRow + PartialEq + 'static> {
    /// The rows to show.
    pub data: ReadSignal<Vec<T>>,
    /// The columns to show them in.
    pub columns: ReadSignal<Vec<Column<T>>>,
    /// Rows per page. Omit to show every row at once.
    #[props(default)]
    pub page_size: Option<usize>,
    /// Whether and how rows can be selected.
    #[props(default)]
    pub selection: SelectionMode,
    /// Whether to show the search box above the grid.
    #[props(default = true)]
    pub searchable: bool,
    /// Whether to show a filter input for every filterable column.
    #[props(default)]
    pub column_filters: bool,
    /// Placeholder for the search box. Defaults to the locale's.
    #[props(default)]
    pub search_placeholder: Option<String>,
    /// What to show when no row matches. Defaults to the locale's.
    #[props(default)]
    pub empty_message: Option<String>,
    /// Every text the grid writes and how it formats numbers and dates, such
    /// as `GridLocale::german()`. English by default.
    #[props(default)]
    pub locale: GridLocale,
    /// Called whenever the set of selected rows changes.
    #[props(default)]
    pub on_selection_change: Option<EventHandler<Vec<T::Key>>>,
    /// Renders only the rows in view, for large data sets. Every row is then
    /// exactly this many pixels tall. Needs `height`, and is usually combined
    /// with no `page_size`.
    #[props(default)]
    pub row_height: Option<f64>,
    /// With `row_height`: extra rows rendered above and below the visible ones.
    /// The default of 20 keeps a fast touch fling from showing blank rows
    /// before the next render; lower it if rendering is expensive.
    #[props(default = 20)]
    pub overscan: usize,
    /// A CSS height for the grid, such as `"480px"`. The grid scrolls within it.
    #[props(default)]
    pub height: Option<String>,
    /// Lets the user resize columns by dragging the edge of a header, or with
    /// `Alt+ArrowLeft` / `Alt+ArrowRight` on a focused header.
    #[props(default = true)]
    pub resizable_columns: bool,
    /// Shows a menu for showing and hiding columns. Columns defined with
    /// `.hidden()` stay hidden and are not listed.
    #[props(default)]
    pub column_picker: bool,
    /// Label of the column menu. Defaults to the locale's.
    #[props(default)]
    pub column_picker_label: Option<String>,
    /// State to start from, such as one saved from `on_state_change`. Read on
    /// the first render only; to apply state loaded later, render the grid once
    /// it is available.
    #[props(default)]
    pub initial_state: Option<GridState>,
    /// Called with the whole state whenever sort, filters, search, page, column
    /// widths or hidden columns change. Serialize it to persist the grid.
    #[props(default)]
    pub on_state_change: Option<EventHandler<GridState>>,
    #[props(extends = GlobalAttributes)]
    pub attributes: Vec<Attribute>,
}

/// A sortable, filterable, pageable data grid.
///
/// ```rust,ignore
/// DataGrid {
///     data: users,
///     columns,
///     page_size: 25,
///     selection: SelectionMode::Multi,
///     on_selection_change: move |keys: Vec<u32>| tracing::info!("{keys:?}"),
/// }
/// ```
#[component]
pub fn DataGrid<T: GridRow + PartialEq + 'static>(props: DataGridProps<T>) -> Element {
    let mut options = GridOptions::default().selection(props.selection);
    options.page_size = props.page_size;
    options.initial_state = props.initial_state.clone();
    options.locale = props.locale.clone();

    let mut grid = use_grid(props.data, props.columns, options);

    let on_state_change = props.on_state_change;
    use_effect(move || {
        let state = grid.state();
        if let Some(handler) = &on_state_change {
            handler.call(state);
        }
    });

    // Report selection changes outward. Reading the keys here is what subscribes
    // the effect to them.
    let on_change = props.on_selection_change;
    use_effect(move || {
        let keys = grid.selected_keys();
        if let Some(handler) = &on_change {
            handler.call(keys);
        }
    });

    let is_empty = grid.filtered_len() == 0;
    let locale = props.locale.clone();
    // Columns defined as hidden are the app's decision, not the user's.
    let pickable: Vec<_> = grid
        .columns()
        .read()
        .iter()
        .filter(|column| column.spec().visible)
        .map(|column| {
            let id = column.id().clone();
            let visible = grid.is_column_visible(&id);
            (id, column.label().to_owned(), visible)
        })
        .collect();
    let last_visible = grid.visible_column_count() <= 1;
    let height_style = props
        .height
        .as_deref()
        .map_or_else(String::new, |height| format!("height: {height};"));

    // Every row is a CSS subgrid of this one track definition, so the header and
    // the cells stay aligned without anyone measuring anything.
    let template = grid
        .visible_columns()
        .iter()
        .map(|column| match grid.column_width(column) {
            ColumnWidth::Auto => match column.spec().min_width {
                Some(min) => format!("minmax({min}px, auto)"),
                None => "minmax(6rem, auto)".to_owned(),
            },
            ColumnWidth::Px(width) => format!("{width}px"),
            ColumnWidth::Fraction(fraction) => format!("{fraction}fr"),
        })
        .collect::<Vec<_>>()
        .join(" ");

    rsx! {
        document::Link { rel: "stylesheet", href: THEME }
        document::Link { rel: "stylesheet", href: STYLE }

        div { class: "dg-wrapper", ..props.attributes,

            if props.searchable || props.column_picker {
                div { class: "dg-toolbar",
                    if props.searchable {
                        GridSearch {
                            grid,
                            class: "dg-search",
                            placeholder: props.search_placeholder.clone(),
                        }
                    }
                    span { class: "dg-count",
                        "{locale.row_count(grid.filtered_len())}"
                        if grid.selected_count() > 0 {
                            ", {locale.selected_count(grid.selected_count())}"
                        }
                    }
                    if props.column_picker {
                        details { class: "dg-columns",
                            summary { {props.column_picker_label.clone().unwrap_or_else(|| locale.columns.to_string())} }
                            div { class: "dg-columns-menu",
                                for (id , label , visible) in pickable {
                                    label { key: "{id}",
                                        input {
                                            r#type: "checkbox",
                                            checked: visible,
                                            // The grid refuses to hide its last column.
                                            disabled: visible && last_visible,
                                            onchange: move |event| grid.set_column_hidden(id.clone(), !event.checked()),
                                        }
                                        "{label}"
                                    }
                                }
                            }
                        }
                    }
                }
            }

            // Outside role="grid" on purpose: a filter row inside it would count
            // towards aria-rowcount and shift every aria-rowindex by one.
            if props.column_filters {
                div { class: "dg-filters",
                    for (index , column) in grid.visible_columns().into_iter().enumerate() {
                        if column.spec().is_filterable() {
                            label { key: "{column.id()}", class: "dg-filter",
                                span { "{column.label()}" }
                                GridColumnFilter { grid, column_index: index, class: "dg-search" }
                            }
                        }
                    }
                }
            }

            div { class: "dg-frame",
                // The grid root is the scroll container: a virtualized body reads
                // its scroll position from there.
                GridRoot {
                    grid,
                    class: "dg",
                    style: "--dg-template: {template}; {height_style}",
                    GridHeader { grid, resizable: props.resizable_columns, class: "dg-head" }
                    if let Some(row_height) = props.row_height {
                        VirtualGridBody {
                            grid,
                            row_height,
                            overscan: props.overscan,
                            class: "dg-body",
                        }
                    } else {
                        GridBody { grid, class: "dg-body" }
                    }
                }
            }

            if is_empty {
                p { class: "dg-empty", role: "status",
                    {props.empty_message.clone().unwrap_or_else(|| locale.no_rows.to_string())}
                }
            }

            GridPagination { grid, class: "dg-pagination" }
        }
    }
}
