#!/usr/bin/env bash
# Copies the registry components into the playground.
#
# The playground renders the components users actually receive, so Playwright
# tests the shipped thing rather than a lookalike. `dx components add` is not
# used here on purpose: it would rewrite the playground's Cargo.toml to depend
# on dioxus-datagrid from git, when inside this workspace it must use the local
# path. `scripts/registry-smoke.sh` covers the real `dx components add` path.
#
# The copies are committed, and CI re-runs this and fails on a diff, so they
# cannot drift from the registry.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

for component in data_grid data_grid_editor data_grid_group_panel; do
  source_dir="$repo_root/registry/$component"
  target_dir="$repo_root/playground/src/components/$component"
  mkdir -p "$target_dir"

  for file in component.rs mod.rs style.css; do
    {
      if [[ "$file" == *.rs ]]; then
        echo "// @generated by scripts/sync-playground-component.sh — do not edit."
        echo "// Edit registry/$component/$file instead."
      else
        echo "/* @generated by scripts/sync-playground-component.sh — do not edit."
        echo " * Edit registry/$component/$file instead. */"
      fi
      cat "$source_dir/$file"
    } > "$target_dir/$file"
  done
done

mkdir -p "$repo_root/playground/assets"
cp "$repo_root/registry/assets/dx-components-theme.css" \
   "$repo_root/playground/assets/dx-components-theme.css"

echo "Synced registry components -> playground/src/components"
