#!/usr/bin/env bash
# Copies the registry component into the playground.
#
# The playground renders the component users actually receive, so Playwright
# tests the shipped thing rather than a lookalike. `dx components add` is not
# used here on purpose: it would rewrite the playground's Cargo.toml to depend
# on dioxus-datagrid from git, when inside this workspace it must use the local
# path. `scripts/registry-smoke.sh` covers the real `dx components add` path.
#
# The copies are committed, and CI re-runs this and fails on a diff, so they
# cannot drift from the registry.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source_dir="$repo_root/registry/data_grid"
target_dir="$repo_root/playground/src/components/data_grid"

mkdir -p "$target_dir" "$repo_root/playground/assets"

for file in component.rs mod.rs style.css; do
  {
    if [[ "$file" == *.rs ]]; then
      echo "// @generated by scripts/sync-playground-component.sh — do not edit."
      echo "// Edit registry/data_grid/$file instead."
    else
      echo "/* @generated by scripts/sync-playground-component.sh — do not edit."
      echo " * Edit registry/data_grid/$file instead. */"
    fi
    cat "$source_dir/$file"
  } > "$target_dir/$file"
done

cp "$repo_root/registry/assets/dx-components-theme.css" \
   "$repo_root/playground/assets/dx-components-theme.css"

echo "Synced registry/data_grid -> playground/src/components/data_grid"
