[package]
name = "playground"
version = "0.1.0"
publish = false
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
dioxus.workspace = true
datagrid-core.workspace = true
dioxus-datagrid = { workspace = true, features = ["serde"] }
serde_json = "1.0.151"

[features]
default = ["web"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]

[lints.rust]
unsafe_code = "forbid"
