// @generated by scripts/sync-playground-component.sh — do not edit.
// Edit registry/data_grid_column_menu/component.rs instead.
//! A menu at every column header of `data_grid`, composed from the unstyled
//! primitive in `dioxus-datagrid`.
//!
//! This file is yours once `dx components add` copies it in. What the menu
//! offers, and what each entry does, lives in the `dioxus-datagrid` crate.

use dioxus::prelude::*;
use dioxus_datagrid::{GridHandle, GridRow};

const STYLE: Asset = asset!("/src/components/data_grid_column_menu/style.css");

/// Props for [`DataGridColumnMenu`].
#[derive(Props, Clone, PartialEq)]
pub struct DataGridColumnMenuProps {}

/// Puts a menu button in every column header of the `DataGrid` around it:
/// sorting, grouping, pinning to either edge, hiding the column, and sizing it
/// back to its content. Name the row type, since nothing else tells the menu
/// which grid it belongs to.
///
/// ```rust,ignore
/// DataGrid { data: users, columns,
///     DataGridColumnMenu::<User> {}
/// }
/// ```
///
/// It renders no markup of its own: it tells the grid that a menu is wanted,
/// and the headers render it. That way the grid does not have to know this
/// component exists, and a project without it compiles none of this.
#[component]
pub fn DataGridColumnMenu<T: GridRow + PartialEq + 'static>(
    props: DataGridColumnMenuProps,
) -> Element {
    let _ = props;
    // Put there by `DataGrid`; outside one there are no headers to add to.
    let Some(grid) = try_use_context::<GridHandle<T>>() else {
        return rsx! {};
    };

    let mut grid = grid;
    use_hook(move || grid.set_column_menu(true));
    use_drop(move || grid.set_column_menu(false));

    rsx! {
        document::Link { rel: "stylesheet", href: STYLE }
    }
}
